---
abstract: "set $r->pnotes('scoreboard_is_full' => 1) if no servers left"
author:
  - 'Fred Moyer <fredmoyer@redhotpenguin.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Apache2-ScoreboardIsFull
no_index:
  directory:
    - t
    - inc
requires:
  Apache::Scoreboard: 0
  mod_perl2: 0
version: 0.01
